version: "3.9"
services:
  telegram:
    image: telegram:0.0.1
    build:
      context: ./telegram
      args:
        - tg_token=6930325282:AAEk7NKx2RP-P_G_7yyYHyY4ucpJrqYbwAM
    depends_on:
      - backend
    networks:
      - seo-network

  backend:
    image: backend:0.0.1
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - seo-network

  postgres:
    container_name: postgres_container
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_DB: "seo-product-cards"
      POSTGRES_USER: "kulikov"
      POSTGRES_PASSWORD: "kulikov"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - seo-product-cards-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kulikov -d seo-product-cards"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - seo-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dakulikov2001@mail.ru"
      PGADMIN_DEFAULT_PASSWORD: "kulikov"
      PGADMIN_CONFIG_SERVER_MODE: "False" # To allow running in desktop mode
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - seo-network

volumes:
  seo-product-cards-db-data:
  pgadmin-data:

networks:
  seo-network:
    driver: bridge
