apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: seo
  name: celery-worker
  labels:
    app: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: kulikov17/seo-backend:0.0.2
        env:
          - name: TG_TOKEN
            valueFrom:
              secretKeyRef:
                name: secret-data
                key: tg_token
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: secret-data
                key: postgres_db
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secret-data
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-data
                key: postgres_password
        ports:
        - containerPort: 8000
        command: ["poetry", "run", "celery", "-A", "src.main.celery", "worker", "-l", "info", "-Q", "model", "--concurrency=1", "-P", "threads"]
        resources:
          limits:
            memory: "2.5Gi"
            cpu: "2"
