apiVersion: v1
kind: Secret
metadata:
  namespace: seo
  name: secret-data
type: Opaque
stringData:
  postgres_db: <ADD DATABASE>
  postgres_user: <ADD USER>
  postgres_password: <ADD PASSWORD>
  tg_token: <ADD TELEGRAM TOKEN>
